I'm sorry, but an uncaught exception occurred.

While loading <renpy.display.im.Image object ("The moment I open the door, I'm greeted with the homely warth of an electric fireplace already permeating from the room. And...?!") at 0x0000000005c395b0>:
  File "game/script.rpy", line 34, in script call
    call pluto_date2b
  File "game/pluto_date2b.rpy", line 191, in script
    "test"
OSError: Couldn't find file 'The moment I open the door, I'm greeted with the homely warth of an electric fireplace already permeating from the room. And...?!'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script call
    call pluto_date2b
  File "game/pluto_date2b.rpy", line 191, in script
    "test"
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 3912, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\core.py", line 2602, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 495, in renpy.display.render.render_screen
  File "render.pyx", line 266, in renpy.display.render.render
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\layout.py", line 884, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\layout.py", line 884, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\layout.py", line 884, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 266, in renpy.display.render.render
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\transform.py", line 747, in render
    return transform_render(self, width, height, st, at)
  File "accelerator.pyx", line 187, in renpy.display.accelerator.transform_render
  File "render.pyx", line 266, in renpy.display.render.render
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\im.py", line 627, in render
    return cache.get(self, render=True)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\im.py", line 295, in get
    surf = image.load()
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\im.py", line 720, in load
    raise e
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\display\im.py", line 685, in load
    filelike = renpy.loader.load(self.filename)
  File "C:\Users\sammiemac\Documents\renpy-8.0.3-sdk\renpy\loader.py", line 820, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'The moment I open the door, I'm greeted with the homely warth of an electric fireplace already permeating from the room. And...?!'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Planetary Pursuits ver.0.2
Thu May  4 12:11:05 2023
