I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/intro2.rpy", line 3, in script
    label intro2:
Exception: Could not find return label (u'game/intro1.rpy', 1668398102, 357).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/intro2.rpy", line 3, in script
    label intro2:
  File "renpy/ast.py", line 1567, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/intro1.rpy', 1668398102, 357).

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Planetary Pursuits ver.0.1
Fri Dec  2 00:49:55 2022
